apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: productcatalog
spec:
  selector:
    matchLabels:
      app: productcatalog
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: productcatalog
    spec:
      containers:
        - name: productcatalog
          image: samfsnow/productcatalog:latest # Image that will be used inside the container in the cluster
          imagePullPolicy: IfNotPresent
          ports:
           - containerPort: 8080 # The port that the container is running on in the clusters